### PR TITLE
Redesign payment (collect/disburse) conversation.

### LINKED ISSUE #985: Disburse/Collect status update shows just one of payments
When milestone payment consists of donation of multiple giver or tokens, multiple PAID donation is created behind the scene. So, one status update should be added per PAID donation.
Currently is not as expected and just the first status update (conversation technically) is accepted by feather.

image

image

### LINKED ISSUE #1041: The amount it says i collected when collecting multiple donations is wrong
https://beta.giveth.io/campaigns/5d2602a167f1fe662d8cee2a/milestones/5da93898d25d7f4a295e3d47

Following #1040 there was another smaller bug...

Screen Shot 2019-10-21 at 11 44 27 AM
I collected about 7000 DAI but its only showing that i collected Samir's donation

### PR DESCRIPTION
**Pull request by aminlatifi**
* Fixes #985
* Fixes #1041

### CODE REVIEW

**Comment by aminlatifi** [comment]
Changes of this pull request should be applied with this one from feather:
https://github.com/Giveth/feathers-giveth/pull/136

**Comment by aminlatifi** [comment]
It also fixes #1040

**Comment by arbreton** [comment]
Im thinking this could be fix with the feathers code update?

**Comment by arbreton** [comment]
Tested on develop with feathers updated, unfortunately the same error

**Comment by aminlatifi** [comment]
> Tested on develop with feathers updated, unfortunately the same error

@arbreton Sorry, I forgot to mention. Conversation records related to payment should be migrated to new format. I have added one script under migrate directory in feather for this purpose. Please run that to transform data in db. You can take a look inside of that script to be confirmed it would do nothing wrong.

**Comment by arbreton** [comment]
@aminlatifi Sounds perfect!, although i think the scripts is not committed on the PR!, did you included that one or should we use an already existing one ?

**Comment by aminlatifi** [comment]
I created a separate one in feather:
https://github.com/Giveth/feathers-giveth/blob/develop/scripts/migrations/migratePaymentConversation.js

**Comment by arbreton** [comment]
It is now on develop but still after the migrations, new collections are showing Unknown, and some of the past milestone broke for some reason 

https://develop.giveth.io/campaigns/5d104191bf3a455a1aebc414/milestones/5dc9d2c7b468b627fc3fa6ae

Capture d’écran 2019-11-11 à 1 58 38 PM

**Comment by aminlatifi** [comment]
image

But it works well for me. Have you cleaned cache? Command+Shift+R in chrome on macos.

**Comment by aminlatifi** [comment]
> @aminlatifi It is now on develop but still after the migrations, new collections are showing Unknown, and some of the past milestone broke for some reason
> 
> https://develop.giveth.io/campaigns/5d104191bf3a455a1aebc414/milestones/5dc9d2c7b468b627fc3fa6ae
> 
> Capture d’écran 2019-11-11 à 1 58 38 PM

Can you give me access to develop db?

**Comment by aminlatifi** [comment]
@arbreton I checked the conversation data receiving from develop. Data is not migrated yet! We should run migration script against develop db.

**Comment by arbreton** [comment]
Ran the script again @aminlatifi, seems to be working!, That record must have been created after i ran the script or something, i will merge it now

**Pull request merged**
