### PR TITLE
dont show popup error if getConversionRate timed out

### PR DESCRIPTION
**Pull request by dehghani-giveth**

### CODE REVIEW

**Comment by dehghani-giveth** [comment]
closes #1609

**Comment by aminlatifi** [comment]
Please show some notification (toast) to user about problem on fetching rates

**Comment by dehghani-giveth** [comment]
> Please show some notification (toast) to user about problem on fetching rates

Done

**Comment by aminlatifi** [comment]
@peymannaderi3 Did you test it yourself?

**Pull request merged**
