### PR TITLE
H 2182 donation comment not shown in trace table

### PR DESCRIPTION
**Pull request by RamRamez**
Issue #2182

### CODE REVIEW

**Comment by aminlatifi** [comment]
image

I guess it would better to align other columns content vertically top. Also for long comments like these one `load more` button seems to be necessary.

**Comment by RamRamez** [comment]
> image
> 
> I guess it would better to align other columns content vertically top. Also for long comments like these one `load more` button seems to be necessary.

Done

**Comment by aminlatifi** [comment]
It should be blue basically
image

**Comment by aminlatifi** [comment]
Donation table is wider and it makes it uneven
image
image

**Comment by RamRamez** [comment]
> Donation table is wider and it makes it uneven
> image
> image

I intentionally made wider to remove horizontal scroll bar

**Comment by aminlatifi** [comment]
Style change has caused some issues in donation table view. 
One is this:
telegram-cloud-photo-size-4-5807760584626779982-y
To have a sense, our current implementation is this:
telegram-cloud-photo-size-4-5807760584626779995-y

Another issue is when the donation table is not empty, it's uneven with rest of page as I mentioned above.

I suggest changing table like this:
image

1. I removed empty not used first column (an empty column has been remained from past and I don't know why!)
2. I removed address column. User address and etherscan link can be obtained by just one click on user name link (4th column)

**Pull request merged**
