### PR TITLE
Fix issue #1349 Ask Anon Donors to fill out a profile

### LINKED ISSUE #1349: Ask Anon Donors to fill out a profile
If it is an anon donor... after the donation is complete we should ask them to make a profile if they want to track their donations and not be anon, I think this can replace the "Thank you for donating, want to donate to giveth" pop up

And then we add the "Thank you for donating, want to donate to giveth" pop up after people make their profile ? 

The challenge there is that we require people to switch their metamask on both moves... but honestly I think its worth it.

### PR DESCRIPTION
**Pull request by horus2021**
Fix #1349 Ask Anon Donors to fill out a profile

### CODE REVIEW

**Comment by aminlatifi** [comment]
@horus2021 I haven't run your code, but it seems new updates doesn't meet #1349 requirements. By your code after donation any user (with/without profile) is asked to support giveth. Then the user is asked to sign in without any pop up! And if user sign in next will be pop up that tells please make profile.

**Comment by horus2021** [comment]
Hey @aminlatifi  check out my commit "Fix issue 1349 2nd try". It works in my local. I send my screen cast of behavior of code via WhatsApp.

**Comment by horus2021** [comment]
Hey @aminlatifi  see[ my latest commit ](https://github.com/Giveth/giveth-dapp/pull/1375/commits/7210479b651a0e9093ccb65baa2f928b6e5497a2). I am not a pro in ReactJS, but it seems that I have fixed the issue. See attached video.
[anon regist h1349 giveth.webm.zip](https://github.com/Giveth/giveth-dapp/files/5068285/anon.regist.h1349.giveth.webm.zip)

**Comment by aminlatifi** [comment]
By reviewing code I guess two popups would be shown at the same time if project is a milestone donating 3% to some DAC.
@horus2021 Can you test above scenario?

**Comment by horus2021** [comment]
Hey @aminlatifi I have an strange problem to test scenario which you suggested. The option to donate 3% to some DAC has been disapeared from develop, but I can see it in beta. See below screen shot.

**beat with option**
Screenshot from 2020-08-13 15-15-28
**develop without option**
Screenshot from 2020-08-13 15-15-36

**Comment by aminlatifi** [comment]
LGTM!

**Pull request merged**
