### PR TITLE
add slug to DAC

### PR DESCRIPTION
**Pull request by mdehghani**

### CODE REVIEW

**Comment by mohammadranjbarz** [comment]
@mdehghani 
I think it would be better to show more clear message when user write a repetive text for milestone title

image

**Comment by mohammadranjbarz** [comment]
image

when proposing new milestone we have id campaignId in url, is it possible to have slug over there?

**Review by mohammadranjbarz — CHANGES_REQUESTED** [review]
It it not supposed to support older links like:
`/campaigns/campaignId/milestones/milestoneId`?
Beucase I think all links that sent to our users is something like that, and if we want deprecate those urls we should change URLs that we send in emails

**Comment by mdehghani** [comment]
> @mdehghani
> I think it would be better to show more clear message when user write a repetive text for milestone title
> 
> image

It would be fixed in another PR

**Comment by mdehghani** [comment]
> image
> 
> when proposing new milestone we have id campaignId in url, is it possible to have slug over there?

As discussed to Amin, we decided to use slug only in 'view' urls.
What do you think Amin? @aminlatifi

**Comment by mdehghani** [comment]
> It it not supposed to support older links like:
> `/campaigns/campaignId/milestones/milestoneId`?
> Beucase I think all links that sent to our users is something like that, and if we want deprecate those urls we should change URLs that we send in emails

Yes, we are supporting old urls now. The mentioned url is supported and will be redirected to the new one. Is there a problem with you?

**Comment by aminlatifi** [comment]
> It it not supposed to support older links like:
> `/campaigns/campaignId/milestones/milestoneId`?
> Beucase I think all links that sent to our users is something like that, and if we want deprecate those urls we should change URLs that we send in emails

In another PR we should redirect all previous links to new one (with slug)

**Comment by aminlatifi** [comment]
> > image
> > when proposing new milestone we have id campaignId in url, is it possible to have slug over there?
> 
> As discussed to Amin, we decided to use slug only in 'view' urls.
> What do you think Amin? @aminlatifi

Yes, it's ok so far. Let's keep it

**Pull request merged**
