### PR TITLE
Fix #645, Delegating to milestones or campaign

### LINKED ISSUE #645: Delegating to milestones is very difficult from the manage page
So many milestones... i need to know what campaign they are coming from... 

ideally I could click a campaign and be given the choice to donate to the campaign itself, or to an individual milestone

### PR DESCRIPTION
**Pull request by xiaods**
The problem:
Right now there are just too many options in this drop down and its confusing cause you dont know what campaigns each milestone listed is in... you only get the title... so you might think you are delegating to a milestone in the giveth communications campaign, but actually you are delegating to the Bloom Campaign (this happened to me!)

proposal:

Make the drop down have 2 levels. The first level being the Campaign and then when you select a campaign, you get to select the milestones in that selected campaign PLUS an option to delegate directly to the campaign itself.

### CODE REVIEW

**Comment by GriffGreen** [comment]
I can't seem to get it to work in netlify @xiaods

**Comment by xiaods** [comment]
@GriffGreen Oops. i have testing it in my local environment , it works like a charm. let a repost again.

**Comment by xiaods** [comment]
屏幕快照 2019-04-03 下午9 30 41

**Comment by xiaods** [comment]
@GriffGreen i found the jenkins is failed. don't know what reason? any insight?

**Comment by xiaods** [comment]
```
Module not found: Error: Can't resolve 'websocket' in '/home/travis/build/Giveth/giveth-dapp/node_modules/web3/node_modules/web3-providers-ws/src'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! giveth-dapp@0.1.0 build: `npm run build-css && react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the giveth-dapp@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-04-03T13_17_05_381Z-debug.log
The command "npm run build" exited with 1.
```

**Comment by xiaods** [comment]
can anyone do me favor?

**Comment by xiaods** [comment]
don't know what reason, no response from team. anyone care about it. please let me know.

**Comment by mroberts10** [comment]
Hi @xiaods let me see if I can get you some help with this.  Sorry for the delay.

**Comment by ElMejorge** [comment]
@xiaods Sorry for the delay in response, we were busy with preparations for a hackathon. Looking at the PR, part of the specification is that when a user chooses a Campaign to delegate to, the milestones shown are only ones pertaining to that Campaign. Could you do this change before I approve the PR?

**Comment by xiaods** [comment]
@ElMejorge thanks for your clarify, i will work on it tomorrow.

**Comment by xiaods** [comment]
@mroberts10  thanks for helps. i will chat in development riot chat.

**Comment by xiaods** [comment]
@ElMejorge  currently codebase already filter the relationship with campaign and milestone, are you can reminder what scope is missing?
屏幕快照 2019-04-16 上午9 17 44

**Comment by ElMejorge** [comment]
@xiaods Yes, what I mean is that when I choose a campaign it should only give me the milestones that relate to that campaign instead of showing me all of the milestones that exist. When a campaign is not selected then it should show all milestones.

All milestones
This is fine when no campaign is selected.

Only campaign milestones
When the campaign "Dancing all day actually" is selected then it should show only three milestones, which are the ones that belong to that campaign.

**Comment by xiaods** [comment]
@ElMejorge  thanks for your clarify, i got it. let me fix it asap.

**Comment by xiaods** [comment]
@GriffGreen could you please give me a hints , how to set campaign input's value, i need help.
```
                 label="Delegate to:"
                  placeholder="Select a Campaign"
                  value={objectsToDelegateToCampaign}
                  options={getCampaignTypes()}
                  onSelect={this.selectedCampaignObject}
                  maxLength={1}
```

**Comment by xiaods** [comment]
@GriffGreen  i have fix it, please review and have a look.

**Comment by xiaods** [comment]
@mroberts10  @GriffGreen  it take long time to review. anyone can take it and give some comments. thanks a lot.

**Pull request merged**
