### PR TITLE
3box integration

### PR DESCRIPTION
**Pull request by santteegt**
Integrate 3Box Profiles into the Giveth Application. Refs #754 

Requires a small change on `feathers-giveth` in PR https://github.com/Giveth/feathers-giveth/pull/109

## Description

Integrates 3box-js to store user profiles on 3Box for free and eliminates current web3 transaction during user registration

## Type of change

- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected): not the dApp does not assign a `giverId` to user profile on feathers. `PledgeAdmins` are not being created on the `LiquidPledging` smart contract.

## Testing

* Almost all dApp features were manually tested on a local environment showing no breaking in user/community/campaign/donations functionality.

## Checklist:

- [X] Make a PR that replaces existing profile infrastructure throughout the Giveth dapp using the 3Box.js API
- [X] Match the look and feel of the Giveth dapp and profile page
- [X] Replace any existing profile transactions, gas fees, etc...
- [X] Allow users to set up and configure a profile on their profile page
- [X] Fetch profiles for users and display them throughout the dapp, where appropriate
- [X] Integrate profile data visually and seamlessly into the rest of the Giveth Dapp
- [X] profiles tightly integrated into the look and feel for Giveth so the experience is seamless; e.g. use the same UI components
- [X] setting up a user profile and adding basic data for Giveth is simple and intuitive
- [X] Integration into the flow of the dapp; e.g. don't have too many/long user stories; keep it simple and clean

### CODE REVIEW

**Comment by GriffGreen** [comment]
we got release up! now fixing develop

**Comment by arbreton** [comment]
Hello @santteegt, excited for this implementation of 3box!, right now it seems that it needs some modifications, i have tried with 2 different accounts and it requests me to sign multiple times, but after i sign it throws this render problem:

Screen Shot 2019-05-23 at 1 12 26 PM

https://develop.giveth.io/ is back online! you can test your implementation here, you just have to modify the .env file on the project like this:

Screen Shot 2019-05-23 at 1 20 47 PM

**Comment by santteegt** [comment]
Hi @arbreton,

I just updated my PR to fix that bug you reported and also include some improvements in the code

**Comment by oed** [comment]
Hey @santteegt Looks like there is some issue with the build getting the error `Allocation failed - JavaScript heap out of memory` we've seen this before with 3Box unfortunately. There are two ways around it. 
1. Increase the memory allocation allowed to be used by the build process
2. Include `3box.min.js` manually in your html (you can add a "postbuild" script that copies the dep from the `node_modules` folder to the `public` folder)

This problems stems from the dependence on js-ipfs and we hope to have it fixed soon 🙂

**Comment by santteegt** [comment]
I´ve updated my PR to include latest changes pushed on the `develop` branch, and a change in the build script to Increase the memory allocation in order to avoid the temporary `JavaScript heap out of memory` issue introduced by 3box

**Comment by michaelsena** [comment]
Great thank you @santteegt. So what are the next steps here?

**Comment by santteegt** [comment]
Hi @arbreton,

Seems that the error wasn't introduced in my PR. Metamask is returning a lower case version of the account address which breaks the `isOwner` evaluation on `src/lib/helpers.jsx`. I've changed that function to not to break app's user permissions

**Comment by santteegt** [comment]
Hi @arbreton,

Just updated my PR to use a better approach to avoid the string case inconsistencies in the account's address [see here](https://github.com/ethereum/web3.js/issues/1395). By using the `web3.utils.toChecksumAddress` function on the `Web3Provider` everything is working as intended b

**Comment by michaelsena** [comment]
@santteegt or @arbreton need anything further from the 3Box side for this? I was wondering when it would be available somewhere for me to test functionality and flows without needing to build the Giveth backend. Can't wait for this one!

**Comment by santteegt** [comment]
Hi @michaelsena,

I'm waiting for them to review my PR. However, their `develop` backend is back online so It is now possible to test the dApp just by specifying `REACT_APP_ENVIRONMENT=develop`  on the `.env` file

**Comment by michaelsena** [comment]
@arbreton any word on this one?

**Comment by arbreton** [comment]
Hello @santteegt, @michaelsena,

Sorry i have been a little absent due to a group gathering, i have checked the pull request again but i cannot compile the code that is currently on the branch, are we missing something?
this is the error that shows up

Screen Shot 2019-06-15 at 2 19 57 AM

**Comment by santteegt** [comment]
Hi @arbreton,

It is a problem related to the following library in the dependency tree:
```
└─ 3box@1.9.0
   └─ ipfs@0.36.3
      ├─ libp2p-kad-dht@0.15.2
```
However, I tried to replicate this error on a new react-app project which comes with react-scripts@3.0.1, and it built the project successfully with no issues. The problem seems to be that you're using a custom version of react-scripts

**Comment by arbreton** [comment]
I tried cloning the repo and running npm install from scratch multiple times it doesn't seem to pass the test, could you be using a global library that is not on the package.json?

**Comment by santteegt** [comment]
@arbreton I've replicated this error by running the dApp on a containerized instance using Docker. Seems that the compilation error was recently introduced by this dependency `libp2p-kad-dht@0.15.2`, but It isn't being thrown when integrating 3box on a React app using one of the latest releases of react-scripts. Who can I get in contact to check if it is enough to implement some changes to your forked version of react-scripts in order to avoid this issue? I don't have any experience customizing/configuring it

**Comment by arbreton** [comment]
Hello @santteegt if react scripts needs to be updated in order for 3box to work feel free to fork and tweak accordingly, then we can merge it if it works fine

Cheers

**Comment by arbreton** [comment]
Hello @santteegt, 
is there any updates on this PR?, do you know what could be conflicting on the dependencies?

**Comment by arbreton** [comment]
Hi @santteegt, 

we would love to merge this pull request, looks a great job!, i think the only thing missing is this dependency situation happening, not sure if you would be available to jump on a call?, please tell me your availability so we can make changes accordingly and coordinate, thank you!

**Comment by santteegt** [comment]
Hi @arbreton,

Sorry I've been AFK & travelling during the last 10 days. Today, I'll arrive at my next destination where I think I can jump to a call and finish this PR. What's your timezone? Do you want me to DM you on Riot?

**Comment by arbreton** [comment]
Hello @santteegt,

Yes of course! we can coordinate on Riot, right now I'm on Pacific Time that will be UTC-8HRS, right now is 5:06PM
Where you will be next?,talk to you soon!

**Comment by mroberts10** [comment]
Update: @santteegt is hoping to fix it soon. Andre has been looking at 3box and believes it is quite good.

**Comment by GriffGreen** [comment]
@santteegt so excited to see how this works! i would love screen shots if its easy :-D or of course if we can get it to work on netlify, i can't wait to play with 3box on Giveth :-D

**Comment by michaelsena** [comment]
We're close, I can feel it! Likewise @GriffGreen, I can't wait to try this one out!

@santteegt assuming you had a chance to sync with the Giveth team on what's required to get this one over the line? :pray:

**Comment by santteegt** [comment]
Hi @arbreton @michaelsena,

I've updated my PR to avoid the compilation error. Changes include branch rebase to include latest changes, while the react-scripts dependency was upgraded to its latest release, so it may have introduced some bugs. However,  for the sake of time, it would be good if you start right away reviewing my code in case you have any comments while I execute do some tests

**Comment by arbreton** [comment]
Hello @santteegt, 

Sounds great!!, of course, i will review and make comments accordingly ASAP

**Comment by GriffGreen** [comment]
should be on develop this week!

**Comment by michaelsena** [comment]
@arbreton mind sharing which message gets repeated? when using 3Box for the first time there are multiple messages to sign, 2-3.

Your should have been given the option to use your existing giveth profile on 3Box and if chosen the giveth data should have been saved to the giveth space on 3Box, including your image. Is this how it was implemented?

cc @santteegt

**Comment by arbreton** [comment]
Hello @michaelsena, 

The first time it popped twice to create a new 3box profile even though i already had a 3box profile strangely!, and after that 3 - 4 sign messages popped out to sign the contract, but that would be the giveth contract 

Which leads me to think there is a memory leak somewhere or a call being repeated requesting sign in multiple times please keep me us @santteegt

**Comment by santteegt** [comment]
Hi @arbreton @michaelsena,

I'm going to check out what is happening with both a fresh account and with another one with an already created 3box profile

**Comment by santteegt** [comment]
Hi @arbreton,

I've just updated my PR to fix a couple of bugs. Basically, there are two different scenarios when users access to Giveth with 3box:

1. **Address with no 3box profile and Giveth profile**: four pop-ups appear with the following requests:

- Request access to view and update your 3box profile
- Request access to open a 3box space called giveth
- Create a new 3box profile
- Sign to register an account on Giveth when accessing the Profile page 

2. **Address with 3box profile and/or Giveth profile**: two pop-ups appear:
- Request access to view and update your 3box profile
- Request access to open a 3box space called giveth

**Comment by arbreton** [comment]
That looks perfect @santteegt ! i will take a look asap, thank you!, ill keep you posted

**Comment by arbreton** [comment]
Hello @santteegt,

It seems to be that it's making the requests multiple times do you know what could be causing this?, also the GET request fails even though i already have a 3box profile

Screen Shot 2019-09-05 at 3 07 03 PM

**Comment by michaelsena** [comment]
@arbreton we (3Box) can help push this over the line, but it'd be easier to cover a lot of the questions in a quick call if you're up for it. We would love to see this get merged since it's been open for so long

**Comment by arbreton** [comment]
That will be awesome @michaelsena!
We are having a call from 10 AM PST to 11AM ~@ 
https://meet.jit.si/giveth-dapp, in 10 minutes or so, we can definitely talk at that time or if you prefer later aswell

**Comment by santteegt** [comment]
Hi guys,

Sorry, I was busy at ETHBoston this weekend. I'm going to review the error @arbreton reported

**Comment by arbreton** [comment]
Hello @santteegt,

Sure! please keep me posted, excited to see this one merged aswell

**Comment by santteegt** [comment]
Hi @arbreton,

The GET 404 errors in the console are being shown for those Giveth user accounts that don't have created a 3box space yet. This usually happens when the UI fetches user data from e.g. Milestones. Current logic tries to fetch user data from 3box, and if not found, requests it from your feathers server. I talked to the 3box team to see how we can avoid this console errors when verifying if an address has a 3box space, but seems that [we can't avoid it at the moment](https://stackoverflow.com/questions/45289441/fetch-still-throws-despite-having-catch-block).

Right now, I'll be running some tests as I've upgraded 3box dependency to its latest version and will update my PR at the end of the day.

**Comment by arbreton** [comment]
We will need to wait for a fix because we can't have an overflow on the developer console!, maybe it doesn't need that many requests?

**Comment by santteegt** [comment]
I think requests are needed to query if an existing Giveth user has migrated her profile info into the giveth 3box space. @michaelsena Do you know if any of your existing use case integrations have implemented a solution to avoid this console errors when an address doesn't have created a 3box space yet? (See https://github.com/Giveth/giveth-dapp/pull/774#issuecomment-531822750)

**Comment by RachBLondon** [comment]
@santteegt as it stands these 404 are needed in our API (other projects rely on them).  @GriffGreen I'm curious to know more about your reason for needing these removed - they wont interfere with the user experience on the site (only appear in the browser).

**Comment by horus2021** [comment]
It seems that this is an outdated issue and we can close it.

**Comment by horus2021** [comment]
It seems that this is an outdated issue and we can close it.

**Pull request closed without merging**
