### PR TITLE
F 2282 Change delegateModal components to Ant

### PR DESCRIPTION
**Pull request by RamRamez**
Issue #2282

### CODE REVIEW

**Comment by aminlatifi** [comment]
https://user-images.githubusercontent.com/5684607/122679863-ccefcd00-d201-11eb-90ac-40c96644fd2f.mov



When I want to delegate a Campaign money, it allows me to select the campaign again in campaign list and then delegating that money to same campaign!

**Review by aminlatifi — CHANGES_REQUESTED** [review]
Please fix issues mentioned

**Comment by RamRamez** [comment]
> image
> 
> They are repetitive items in campaigns list when I want to delegate community money

Develop also has this problem.
image

**Comment by RamRamez** [comment]
>  Delegate-smaller.mov 
> When I want to delegate a Campaign money, it allows me to select the campaign again in campaign list and then delegating that money to same campaign!

Done.

**Comment by aminlatifi** [comment]
LGTM!

**Pull request merged**
