### PR TITLE
Update JoinGivethCommunity.jsx

### PR DESCRIPTION
**Pull request by krrisis**
fixed dead link (https)

### CODE REVIEW

**Comment by vojtechsimetka** [comment]
Deploy preview for *giveth-dapp* processing.

Built with commit cdf29562eef6c4703303e25814bdc0aa9d5dca62

https://app.netlify.com/sites/giveth-dapp/deploys/5bbf59e3c965922f9c0733e8

**Comment by vojtechsimetka** [comment]
Hey @krrisis, I think we better try and fix the https issue first :).

**Comment by krrisis** [comment]
Https://giveth.io/join is where it redirects so nothing to fix there, https works! 🙂

**Comment by vojtechsimetka** [comment]
Yeah but you changed the button to redirect to http and not https . Please change that to https://giveth.io/join

**Comment by vojtechsimetka** [comment]
never mind just did

**Comment by krrisis** [comment]
thanks man - yeah should prob just have done that. 🙈 happy it's figured out now

**Pull request merged**
