### PR TITLE
Prettier

### LINKED ISSUE #203: Add Prettier and Prettier ESLint
### User Story

User story 1: As a developer, I don't want to have to worry about formatting styles. I want code to autoformat whenever I save. I want to completely remove any thinking of formatting from my workflow.

User story 2: As a reviewer, I want to ensure that code is formatted correctly and I don't have to review formatting errors and comment on them.

*Type*: Developer Tool

### Summary: Integrate Prettier and Prettier ESLint into the project. 
There are multiple editor integrations such as VSCode, Sublime, Atom, Vim and more.
In addition with Prettier ESLint we can get the power of ESLint --fix to automatically fix Prettier errors automatically even when not using any plugins.

*Links:*
https://github.com/prettier/prettier/
https://prettier.io/
https://prettier.io/docs/en/eslint.html

### Expected behavior

While coding I have a formatting style guide that I am forced to follow and if I don't I get linting errors which could potentially break builds.

Actual behavior

Currently developers have to think about maintaining the current style of formatting and coding and thinking hard about this wastes time to think of other more important problems.

### Solution

*Summary:*

I will add Prettier and Prettier ESLint integration and write up a Formatting.md file to explain how to use this in a few editors of choice.

### Additional Information

This is open to suggestions/feedback.

### PR DESCRIPTION
**Pull request by Alonski**
Fixes #203 
This is the first iteration.
We can decide on a coding style and just go with it.
Prettier and ESLint can be configured but we just need to decide what we want.
I currently went with defaults expect:
Single Quotes instead of Double
Trailing Comma always

I added ESLint Plugins so ESLint --fix also fixes Prettier errors

In addition I added VSCode Settings that helps develop with ESLint and Prettier. This can be removed but I think it does help during development.

I also noticed some ESLint errors about console.log statements but maybe these will be removed from production or we can add a build step to remove them from production. and then ignore this rule?

I would love some feedback 😄

### CODE REVIEW

**Comment by perissology** [comment]
I'd prefer not to commit editor setting as not everyone uses the same editor. Maybe we can put them in the wiki or something.

**Comment by Alonski** [comment]
@perissology So just remove the vscode settings?
I am planning on creating a FORMATTING.md for this in the future. Or a Wiki if that is what is needed.

**Comment by perissology** [comment]
yes on vscode settings. only other thing is just make sure that the linting changes you made still pass the airbnb eslint. I suspect that some do not, but I could be wrong

FORMATTING.md is perfect for the settings

**Comment by Alonski** [comment]
This integrates with ESLint so they work together. 😀

**Comment by Alonski** [comment]
@perissology I removed the settings file and created a very basic `FORMATTING.md`

**Comment by perissology** [comment]
Thanks. We've rewarded you with 50 DAPP points for the reward DAO from 12/15 - 1/15 :+1:

**Comment by perissology** [comment]
also, if you want to add the prettier/eslint config stuff to [feathers repo](https://github.com/Giveth/feathers-giveth) that'd be great!

**Comment by Alonski** [comment]
Awesome thanks! I'll get it up and running on feather as well

**Pull request merged**
