### PR TITLE
F 1353 show value in native currency

### PR DESCRIPTION
**Pull request by mdehghani**
@aminlatifi

### CODE REVIEW

**Comment by aminlatifi** [comment]
The usd value is not correct for ETH
image

**Comment by aminlatifi** [comment]
@mdehghani Please merge latest develop branch into your branch before creating pull request. This one has conflict with develop branch

**Review by aminlatifi — CHANGES_REQUESTED** [review]
Resolve conflicts

**Comment by aminlatifi** [comment]
image
If I choose new currency the ETH price is zero.

**Comment by mdehghani** [comment]
take a look at new commits
@aminlatifi

**Comment by aminlatifi** [comment]
@mdehghani I fill it would be better to get rates one by one. I have several reasons for this decision,
1. It maybe more performant on backend
2. We use USD rates for stable coins (like DAI), but now it has different value for usd and dai native currency

**Review by aminlatifi — APPROVED** [review]

**Pull request merged**
