### PR TITLE
F 2544 ability to withdraw any tokens bigger than withdraw limit

### PR DESCRIPTION
**Pull request by RamRamez**
Issue #2544

### CODE REVIEW

**Comment by mohammadranjbarz** [comment]
@RamRamez 
You didnt handle withdraw when user want to withdraw from /my-traces

Screen Shot 1400-07-06 at 17 03 25

**Comment by MoeNick** [comment]
Do you have any suggestion @mohammadranjbarz ?

**Comment by RamRamez** [comment]
@mohammadranjbarz 
When there is only one token to withdraw, that token is selected by default and select component is disabled.
I can remove select component in this case and just a text instead

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz When there is only one token to withdraw, that token is selected by default and select component is disabled. I can remove select component in this case and put just a text instead

@MoeNick 
What do you think about it ?

**Comment by RamRamez** [comment]
> @RamRamez You didnt handle withdraw when user want to withdraw from /my-traces
> 
> Screen Shot 1400-07-06 at 17 03 25

Yes you're right. I fixed it.

**Comment by mohammadranjbarz** [comment]
> > @RamRamez You didnt handle withdraw when user want to withdraw from /my-traces
> > Screen Shot 1400-07-06 at 17 03 25
> 
> Yes you're right. I fixed it.

It's ok now
but I get an error when want to disburse money

Screen Shot 1400-07-07 at 09 42 04 (2)

**Comment by RamRamez** [comment]
@mohammadranjbarz I simulated the same situation and it was ok for me. Maybe it was a MetaMask error or something. Can you test again?

**Review by mohammadranjbarz — APPROVED** [review]
Thanks, Looks good to me

**Review by mohammadranjbarz — APPROVED** [review]

**Review by mohammadranjbarz — APPROVED** [review]
@RamRamez 
Thanks, it seems good

**Pull request merged**
