### PR TITLE
H 1666 fix user profile form

### PR DESCRIPTION
**Pull request by peymannaderi3**

### CODE REVIEW

**Comment by peymannaderi3** [comment]
#1666

**Comment by aminlatifi** [comment]
@Thanks, it as we expected
There is a bug which appears in this scenario:

1. Updated Email
2. Pressed submit button
3. Did the transaction
4. New data is uploaded as new object to IPFS and the hash value is saved in smart contract
5. But the database (feathers) `url` entry (IPFS value) is not updated.

**Comment by aminlatifi** [comment]
> @thanks, it as we expected
> There is a bug which appears in this scenario:
> 
> 1. Updated Email
> 2. Pressed submit button
> 3. Did the transaction
> 4. New data was uploaded as new object to IPFS and the hash value was saved in smart contract
> 5. But the **database (feathers) `url` entry (IPFS value) was not updated.**

I was wrong, URL field is updated later in backend.

**Comment by aminlatifi** [comment]
Seems OK

**Pull request merged**
