### PR TITLE
F 2028 redesign accept proposal write comment modals

### PR DESCRIPTION
**Pull request by RamRamez**
Issue #2028

### CODE REVIEW

**Comment by aminlatifi** [comment]
@RamRamez Thank you Ramin, I believe animations should be stopped after first run

**Comment by aminlatifi** [comment]
@RamRamez Thanks, they are great. Can you make them to appear in center?

**Comment by RamRamez** [comment]
> @RamRamez Thanks, they are great. Can you make them to appear in center?

Done.

**Comment by aminlatifi** [comment]
Looks good and beautiful, thanks @markoprljic @RamRamez

**Pull request merged**
