### PR TITLE
Set limit for every currency for withdraw

### PR DESCRIPTION
**Pull request by mohammadranjbarz**
related to #1887 #1886

### CODE REVIEW

**Comment by aminlatifi** [comment]
Seems OK, thanks @mohammadranjbarz 
@MoeNick should be tested

**Comment by aminlatifi** [comment]
@mohammadranjbarz isAmountEnoughForWithdraw is not passed as attribute somewheres
@MoeNick It's not ready for test until above line issue is fixed

**Comment by MoeNick** [comment]
> @mohammadranjbarz isAmountEnoughForWithdraw is not passed as attribute somewheres
> @MoeNick It's not ready for test until above line issue is fixed

pls let me know when I can test.. and pleeeeeeeeeeeeeeeeese set estimates! :)

**Comment by mohammadranjbarz** [comment]
> > @mohammadranjbarz isAmountEnoughForWithdraw is not passed as attribute somewheres
> > @MoeNick It's not ready for test until above line issue is fixed
> 
> pls let me know when I can test.. and pleeeeeeeeeeeeeeeeese set estimates! :)

@MoeNick The zenhub shows PRs as issues, but they are not realy issues and they are some codes that connected to some other issues that they have estimates:
https://github.com/Giveth/giveth-dapp/pull/1992#issue-610313345

**Pull request merged**
