### PR TITLE
[WIP] add matrix room creation

### LINKED ISSUE #526: Create a matrix room for every new Campaign and DAC
I would love to have the riot chats created for every Campaign and DAC so by default a riot room is created in the name of the campaign and displayed prominently on the page (as well as sent to all the participants)... this can be bridged to telegram, gitter, mattermost, slack, and many other social media platforms!

So by default a riot room is created in the name of the campaign and the link to the room is displayed prominently on the page (as well as sent to all the donors, the reviewer, etc)... this can be bridged to telegram, gitter, mattermost, slack, and many other social media platforms!

This is the first milestone of a larger effort to start pushing the creation of communities on top of the giveth dapp.

For this milestone to be complete there are three parts that need to be done:

1. Create a new matrix room upon a user creating the campaign/dac while leaving their other social channel link input as an option. 
2. Show the riot link prominently to the user after they create the Campaign/DAC and encourage them to join it as well as the Giveth Communities Channel 
3. Display the Riot link on the Campaign page and on the user's profile page, as well as the fact that they are the Manager/Delegate for the Campaign/DAC.

### PR DESCRIPTION
**Pull request by lsaether**
closes #526 

screenshot_20190227_205408

- [x] creates a new Matrix room for every campaing / DAC if one doesn't yet exist. 
- [x] Display prominent button next to other social button linking to the Riot room

### CODE REVIEW

**Comment by lsaether** [comment]
Depends on https://github.com/Giveth/feathers-giveth/pull/106 in `feathers-giveth`

**Comment by GriffGreen** [comment]
Fuck yeah! Cool man!

**Comment by ewingrj** [comment]
is this ready for review or are you still working on this?

**Comment by lsaether** [comment]
@ewingrj hey been meaning to circle back to this! going to add a few more things and then will ping for review.

**Comment by GriffGreen** [comment]
there also will be an admin question... 
the bot making the room ends up as an admin... how do we fix that?
it seems like the bot would need to make the first person to join the room an admin...

**Comment by GriffGreen** [comment]
@lsaether there is a dapp meeting at 6pm Barcelona time if you had any questions about this :-)
https://meet.jit.si/giveth-dapp

**Comment by arbreton** [comment]
Reviewed this branch, created a campaign but it's not creating a matrix room, still needs some work to be done

**Comment by GriffGreen** [comment]
Still not done

**Comment by arbreton** [comment]
Will reopen when work is resumed

**Pull request closed without merging**
