### PR TITLE
Fixes #475: Milestones that have no funding get marked complete and then can't receive funding

### LINKED ISSUE #475: Milestones that have no funding get marked complete and then can't receive funding
There are many solutions to this very common error. 
Options:
1. Milestones cannot be marked complete unless they have some funding
2. If a Milestone has no funding an extra warning box comes up when marking it complete
3. **Even if a milestone is marked complete, the UI allows for funds to be sent to it.**

Each of these has its own pros and cons... My fave is 2 but any solution including one not listed here is fine :-D

### PR DESCRIPTION
**Pull request by millnitzluan**
This PR is to close the issue #475 
I've displayed button "DONATE" when milestone have been completed but still not fully funded

### CODE REVIEW

**Comment by millnitzluan** [comment]
@vojtechsimetka is what are u waiting for?

**Comment by vojtechsimetka** [comment]
Deploy preview for *giveth-dapp* processing.

Built with commit 1d73ddd77ebcc9fce5ddd578ac696abaced076bc

https://app.netlify.com/sites/giveth-dapp/deploys/5bc121f2e39e7c086089b018

**Comment by vojtechsimetka** [comment]
Hey @millnitzluan did you try if it works? I am afraid it is sadly not that easy (otherwise we would do it). If I try to donate to a completed milestone, the donation actually does not get there and looks like this:
screen shot 2018-10-13 at 12 07 20

Also I think you should allow donating when in the NeedsReview state as well.
screen shot 2018-10-13 at 12 03 40

**Comment by millnitzluan** [comment]
I'm going to check this

**Comment by millnitzluan** [comment]
@vojtechsimetka I'm getting some problems trying to test this in ropsten network, I don't know if it's a problem from the network or the app

**Comment by vojtechsimetka** [comment]
@millnitzluan That means that feathers can not process those transactions. You will need to run that locally and investigate. https://github.com/Giveth/feathers-giveth

**Comment by millnitzluan** [comment]
Well, I'm thinking that I'll to change something in the client.

**Comment by millnitzluan** [comment]
I'm getting this error:  `error: donation has status === `Pending` but home transaction was successful. Was the donation correctly bridged?`.
Maybe the contract doesn't allow it?

**Comment by vojtechsimetka** [comment]
@millnitzluan I think @perissology is the one who could help indicate where the problem may be.

> Maybe the contract doesn't allow it?

Please check that :). But I would expect the problem to be in the https://github.com/Giveth/feathers-giveth/blob/develop/src/blockchain/pledges.js . You can make transactions reprocess if you erase Donations and Events and restart feathers. This is very painful to debug, sorry for that.

**Comment by millnitzluan** [comment]
I didn't find the reason, I'm thinking to close this PR and stop working in gitcoin, so others can help :)

**Pull request closed without merging**
