### PR TITLE
Fixes #523: Add share options on all views

### LINKED ISSUE #523: Share option added for milestones and campaigns
Add a prefilled tweeeeeter link, FB link, telegram link, Insta link.... and whatever other fun social media platform... so people can easily share the web page they are using to raise funds.

### PR DESCRIPTION
**Pull request by anshumanv**
Fixes #523 

Added a share section at the bottom of each view listing some share options.

If testing locally, secured links can't be shared on some apps so please change the props to some secured link.

### CODE REVIEW

**Comment by anshumanv** [comment]
@GriffGreen @vojtechsimetka please see if this looks apt. :smile:

**Comment by vojtechsimetka** [comment]
@GriffGreen is this how you wanted it? https://5c00cff8ec8a89724cb3126f--giveth-dapp.netlify.com/?_ga=2.59806701.1715091526.1543675440-25499042.1491828878

**Comment by vojtechsimetka** [comment]
@griffgreen this is fine by me, i’ll merge if I don’t hear anything from you on wednesday so that @anshumanv can get his reward.

**Comment by anshumanv** [comment]
@vojtechsimetka @GriffGreen you can go ahead with this if you'd like, I'll make any requested/suggested changes if needed after this is merged as per the preference. 😄

**Comment by anshumanv** [comment]
Ah read the conversation, making changes 👍

**Pull request merged**
