### PR TITLE
F 2233 Donation Modal Redesign

### PR DESCRIPTION
**Pull request by RamRamez**
Issue #2233 #2384 

1. Donation Modal Redesign
2. Unlocking Process Modal
3. Fix not showing token balance on donate refresh
4. Optimising DonateButtonModal.jsx

### CODE REVIEW

**Review by aminlatifi — CHANGES_REQUESTED** [review]
Thanks @RamRamez, good job
These issues should be addressed:
1. Please use Ant Design buttons, their loading is far better than bootstrap buttons and also we have plan to remove bootstrap from our project
2. The scenario implemented does not match with this:
https://github.com/Giveth/giveth-dapp/issues/2233#issuecomment-879802618
In concise, User should see button with text of `Approve`. After click and signing transaction button should be in loading and disabled state. After transaction is confirmed the button becomes active with `Donate` text and user should click it again.

**Comment by RamRamez** [comment]
> Thanks @RamRamez, good job
> These issues should be addressed:
> 
> 1. Please use Ant Design buttons, their loading is far better than bootstrap buttons and also we have plan to remove bootstrap from our project
> 2. The scenario implemented does not match with this:
>    [Donation Modal Redesign #2233 (comment)](https://github.com/Giveth/giveth-dapp/issues/2233#issuecomment-879802618)
>    In concise, User should see button with text of `Approve`. After click and signing transaction button should be in loading and disabled state. After transaction is confirmed the button becomes active with `Donate` text and user should click it again.

Done

**Comment by aminlatifi** [comment]
In donating to trace scenario, donate to community is not shown if trace has a community to donate 3% to it

**Comment by RamRamez** [comment]
> In donating to trace scenario, donate to community is not shown if trace has a community to donate 3% to it

It seems its OK

**Comment by aminlatifi** [comment]
Seems OK, thanks @RamRamez

**Pull request merged**
