### PR TITLE
[FIX #229] formatting issue when editing

### LINKED ISSUE #229: formatting issue when editing
when you edit a milestone/campaign etc, it screws up formatting: all line spaces disappear and everything is pasted together.

reproduce:

- edit any milestone
- you see spaces between paragraphs disappear

### PR DESCRIPTION
**Pull request by ovx**
Fixes #299 via https://github.com/Giveth/feathers-giveth/pull/91

### CODE REVIEW

**Comment by vojtechsimetka** [comment]
Deploy preview for *giveth-dapp* processing.

Built with commit e03bf0fd3019eb5d24ae7be3dbd3a129c2ed3620

https://app.netlify.com/sites/giveth-dapp/deploys/5b0405d4c9659253bf99c735

**Comment by vojtechsimetka** [comment]
Deploy preview for *giveth-dapp* processing.

Built with commit e03bf0fd3019eb5d24ae7be3dbd3a129c2ed3620

https://app.netlify.com/sites/giveth-dapp/deploys/5b0405d41f12b721b65885da

**Comment by vojtechsimetka** [comment]
@geleeroyale I believe this is something needed for the open bounties. Let me know how I can help or if we sort it out together?

**Comment by geleeroyale** [comment]
@vojtechsimetka all good - this is an empty commit needed for the bounty

**Pull request merged**
