### PR TITLE
Removing props, including UserProvider

### PR DESCRIPTION
**Pull request by rudin**
in progress

### CODE REVIEW

**Comment by vojtechsimetka** [comment]
Deploy preview for *giveth-dapp* processing.

Built with commit 190b768bd6e18ade4bc4e0f4f8c09e748a430fa5

https://app.netlify.com/sites/giveth-dapp/deploys/5afc3a59dd6a54681cd18f65

**Comment by vojtechsimetka** [comment]
Deploy preview for *giveth-dapp* processing.

Built with commit 190b768bd6e18ade4bc4e0f4f8c09e748a430fa5

https://app.netlify.com/sites/giveth-dapp/deploys/5afc3a5add6a546dacd18f64

**Comment by vojtechsimetka** [comment]
@rudin Are you still working on this?

**Comment by rudin** [comment]
Hi Vojteck, was hoping to pick it up sooner than later, but the changes can surely be merged, no breaking changes and just merged all changes from develop into this branch.

**Pull request merged**
