### PR TITLE
[WIP] Fix: Milestone And Campaign Reviewer Management

### PR DESCRIPTION
**Pull request by iamonuwa**
Setup Modal for changing reviewer in Campaigns and Milestones

Fixes: #489

### CODE REVIEW

**Comment by vojtechsimetka** [comment]
Deploy preview for *giveth-dapp* processing.

Built with commit a771aa2f3bac91b3fc4d113ef09950a79c408cf3

https://app.netlify.com/sites/giveth-dapp/deploys/5bc4a8deb3127429a3038233

**Comment by vojtechsimetka** [comment]
Deploy preview for *giveth-dapp* processing.

Built with commit a771aa2f3bac91b3fc4d113ef09950a79c408cf3

https://app.netlify.com/sites/giveth-dapp/deploys/5bc4a8dedd28ef25af485e13

**Comment by vojtechsimetka** [comment]
@iamonuwa Hey, just wanted to make sure, this is not completed yet, right?

**Comment by iamonuwa** [comment]
> @iamonuwa Hey, just wanted to make sure, this is not completed yet, right?

No its not. Work in progress.

I left a comment for you https://github.com/Giveth/giveth-dapp/issues/489#issuecomment-430445361

**Comment by iamonuwa** [comment]
@vojtechsimetka how do I get the new reviewer's details. Any field to show that you have been requested to become a reviewer? Am asking this because the new reviewer needs to accept the review request.

**Comment by vojtechsimetka** [comment]
@iamonuwa we do have a whitelist in the DApp who can the new reviewer be. It is in the src/providers/userprovider . So selecting new reviewer should just be picking someone from that list. Just so you know how it looks like, it is also exposed publicly https://feathers.beta.giveth.io/whitelist

**Comment by iamonuwa** [comment]
@vojtechsimetka I get that and have gone past this. At the moment, I can select a new reviewer from the list. Where am stuck is how to know when to display the second requirement to the new reviewer
`Add Accept Reviewer Role button for Campaigns`
and 
`Add Accept Reviewer Role button for Milestones`

Am not supposed to expose this for every reviewer on the list. 
I need to know if there is any field to show who the new reviewer is.

**Comment by iamonuwa** [comment]
@vojtechsimetka are you there?

**Comment by vojtechsimetka** [comment]
Yeah, what is your question @iamonuwa ?

**Comment by iamonuwa** [comment]
> No you would have to add that to the feathers caching server once the current reviewer selects new reviewer.

Didn't see this before sending the last message. 

Thank you. I get it now. I'll need to patch the service to update the reviewer fields.

Was thinking there is a way to show this is a new reviewer. So that the reviewer can accept

**Comment by iamonuwa** [comment]
@vojtechsimetka according to this lines, 
https://github.com/Giveth/feathers-giveth/blob/c8c4c789be2f55d12afff1aab4010b2ba5209e3b/src/services/campaigns/campaigns.hooks.js#L47

https://github.com/Giveth/feathers-giveth/blob/c8c4c789be2f55d12afff1aab4010b2ba5209e3b/src/services/campaigns/campaigns.hooks.js#L56

at the moment, a reviewer can only update the status or mined status of a transaction. Can't update the reviewer. Can you confirm this?

**Comment by iamonuwa** [comment]
@vojtechsimetka are you there?

**Comment by vojtechsimetka** [comment]
@iamonuwa yes that is correct. Reviewers are currently limited to only update those fields. You will need to change it.

**Comment by iamonuwa** [comment]
> @iamonuwa yes that is correct. Reviewers are currently limited to only update those fields. You will need to change it.

You mean, I'll need to send in a PR to the feathers-giveth api?

**Comment by vojtechsimetka** [comment]
Yes. You will have to change these things in feathers and you will have to create 2 PRs. We were considering making a mono repo, but did not get to it yet.

**Comment by iamonuwa** [comment]
> Yes. You will have to change these things in feathers and you will have to create 2 PRs. We were considering making a mono repo, but did not get to it yet.

Alright, fixing them right now. Will soon send in PRs for the two

**Comment by vojtechsimetka** [comment]
Hi @iamonuwa are you still working on this?

**Comment by iamonuwa** [comment]
> Hi @iamonuwa are you still working on this?

Yes @vojtechsimetka am working on it. ETA is this weekend

**Comment by iamonuwa** [comment]
Was away during the weekend. Work is currently in progress

**Comment by vojtechsimetka** [comment]
Hi @iamonuwa are you still working on this?

**Comment by iamonuwa** [comment]
@vojtechsimetka yes, I'll wrap this up this weekend

**Comment by vojtechsimetka** [comment]
Closed on accident

**Comment by iamonuwa** [comment]
@vojtechsimetka apologies for the taking longer time to respond. Am going to close this PR and raise a new one with the issue resolved in it.

**Comment by iamonuwa** [comment]
My branch is really outdated and will cause a lot of merge conflicts. So am going to rebase and continue with the current updates

**Pull request closed without merging**
