### PR TITLE
F 2052 Frontend implementation for search bar inside campaign

### PR DESCRIPTION
**Pull request by RamRamez**
Issue #2052

### CODE REVIEW

**Comment by aminlatifi** [comment]
Buttons and search input is different than design
image

image

**Comment by aminlatifi** [comment]
The search file animation just should be played during search, and after the result is ready it should be a static image
image

**Comment by RamRamez** [comment]
> The search file animation just should be played during search, and after the result is ready it should be a static image
> image

Done

**Comment by aminlatifi** [comment]
Thanks @RamRamez. For the search input please implement `debounce` input. Currently by every button hit a new search is triggered.

**Pull request merged**
